"""Add bypass_login_otp to User model

Revision ID: 6a6ccef8135c
Revises: 457d769bfd54
Create Date: 2025-11-27 22:37:02.034813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6ccef8135c'
down_revision = '457d769bfd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bypass_login_otp', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bypass_login_otp')

    # ### end Alembic commands ###
