"""Add login OTP fields to User

Revision ID: 9a52ff1783e9
Revises: 500ae7c7acb0
Create Date: 2025-11-23 12:55:52.340500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a52ff1783e9'
down_revision = '500ae7c7acb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('login_otp_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('login_otp_expires')
        batch_op.drop_column('login_otp')

    # ### end Alembic commands ###
