"""Add otp_secret to User model

Revision ID: a204a41075de
Revises: 82b2d4dc937e
Create Date: 2025-11-08 22:31:27.125303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a204a41075de'
down_revision = '82b2d4dc937e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))
        batch_op.create_unique_constraint(None, ['otp_secret'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
