"""Perbesar ukuran kolom otp_secret

Revision ID: a8080c2960a0
Revises: a204a41075de
Create Date: 2025-11-08 23:28:44.495618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8080c2960a0'
down_revision = 'a204a41075de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_secret',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('otp_secret',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
